### ISSUE TITLE
settings.DATABASES is improperly configured. Please supply the ENGINE value

### ISSUE THREAD

**Issue by songproducer** [davit-gh/ecommerce#2]
>django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by songproducer** [comment]
When using sqlite3 I get this:

>django.db.utils.OperationalError: unable to open database file

**Comment by songproducer** [comment]
Thanks very much, I just need to wait a few days for my blockchain api to be approved.

**Comment by davit-gh** [comment]
You're welcome! I assume this issue is resolved. Please open another one if you encounter any other errors.

**Comment by mbuhfranklin** [comment]
am facing this error
ERRORS:
<class 'main.admin.HomepageAdmin'>: (admin.E012) There are duplicate field(s) in 'fieldsets[0][1]'.
